using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IconManager
{
    /// <summary>
    /// Contains data and information for the WinUI/UWP Symbol enum.
    /// </summary>
    /// <remarks>
    /// This is not currently an IconSet and only contains WinUI/UWP Symbol enum values.
    /// </remarks>
    public class WinUISymbols
    {
        /// <summary>
        /// Defines constants that specify a glyph from the a Microsoft symbol icon font.
        /// </summary>
        /// <remarks>
        /// Last updated for Windows version: 1709, SDK version: 16299.
        /// See: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.symbol?view=winrt-22000.
        /// 
        /// The symbol enum originated with the v1 Segoe UI Symbol font. However, it was
        /// then updated with four additional symbols GlobalNavigationButton, Print, Share and XboxOneConsole
        /// which are only available starting in the v2 Segoe MDL2 Assets font with Windows 10 1709.
        /// This means that this Symbol enum should only really be used with Segoe MDL2 Assets or higher fonts.
        /// </remarks>
        public enum Symbol
        {
            Accept = 0xE10B,
            Account = 0xE168,
            Add = 0xE109,
            AddFriend = 0xE1E2,
            Admin = 0xE1A7,
            AlignCenter = 0xE1A1,
            AlignLeft = 0xE1A2,
            AlignRight = 0xE1A0,
            AllApps = 0xE179,
            Attach = 0xE16C,
            AttachCamera = 0xE12D,
            Audio = 0xE189,
            Back = 0xE112,
            BackToWindow = 0xE1D8,
            BlockContact = 0xE1E0,
            Bold = 0xE19B,
            Bookmarks = 0xE12F,
            BrowsePhotos = 0xE155,
            Bullets = 0xE133,
            Calculator = 0xE1D0,
            Calendar = 0xE163,
            CalendarDay = 0xE161,
            CalendarReply = 0xE1DB,
            CalendarWeek = 0xE162,
            Camera = 0xE114,
            Cancel = 0xE10A,
            Caption = 0xE15A,
            CellPhone = 0xE1C9,
            Character = 0xE164,
            Clear = 0xE106,
            ClearSelection = 0xE1C5,
            Clock = 0xE121,
            ClosedCaption = 0xE190,
            ClosePane = 0xE127,
            Comment = 0xE134,
            Contact = 0xE13D,
            Contact2 = 0xE187,
            ContactInfo = 0xE136,
            ContactPresence = 0xE181,
            Copy = 0xE16F,
            Crop = 0xE123,
            Cut = 0xE16B,
            Delete = 0xE107,
            Directions = 0xE1D1,
            DisableUpdates = 0xE194,
            DisconnectDrive = 0xE17A,
            Dislike = 0xE19E,
            DockBottom = 0xE147,
            DockLeft = 0xE145,
            DockRight = 0xE146,
            Document = 0xE130,
            Download = 0xE118,
            Edit = 0xE104,
            Emoji = 0xE11D,
            Emoji2 = 0xE170,
            Favorite = 0xE113,
            Filter = 0xE16E,
            Find = 0xE11A,
            Flag = 0xE129,
            Folder = 0xE188,
            Font = 0xE185,
            FontColor = 0xE186,
            FontDecrease = 0xE1C6,
            FontIncrease = 0xE1C7,
            FontSize = 0xE1C8,
            Forward = 0xE111,
            FourBars = 0xE1E9,
            FullScreen = 0xE1D9,
            GlobalNavigationButton = 0xE700,
            Globe = 0xE12B,
            Go = 0xE143,
            GoToStart = 0xE1E4,
            GoToToday = 0xE184,
            HangUp = 0xE137,
            Help = 0xE11B,
            HideBcc = 0xE16A,
            Highlight = 0xE193,
            Home = 0xE10F,
            Import = 0xE150,
            ImportAll = 0xE151,
            Important = 0xE171,
            Italic = 0xE199,
            Keyboard = 0xE144,
            LeaveChat = 0xE11F,
            Library = 0xE1D3,
            Like = 0xE19F,
            LikeDislike = 0xE19D,
            Link = 0xE167,
            List = 0xE14C,
            Mail = 0xE119,
            MailFilled = 0xE135,
            MailForward = 0xE120,
            MailReply = 0xE172,
            MailReplyAll = 0xE165,
            Manage = 0xE178,
            Map = 0xE1C4,
            MapDrive = 0xE17B,
            MapPin = 0xE139,
            Memo = 0xE1D5,
            Message = 0xE15F,
            Microphone = 0xE1D6,
            More = 0xE10C,
            MoveToFolder = 0xE19C,
            MusicInfo = 0xE142,
            Mute = 0xE198,
            NewFolder = 0xE1DA,
            NewWindow = 0xE17C,
            Next = 0xE101,
            OneBar = 0xE1E6,
            OpenFile = 0xE1A5,
            OpenLocal = 0xE197,
            OpenPane = 0xE126,
            OpenWith = 0xE17D,
            Orientation = 0xE14F,
            OtherUser = 0xE1A6,
            OutlineStar = 0xE1CE,
            Page = 0xE132,
            Page2 = 0xE160,
            Paste = 0xE16D,
            Pause = 0xE103,
            People = 0xE125,
            Permissions = 0xE192,
            Phone = 0xE13A,
            PhoneBook = 0xE1D4,
            Pictures = 0xE158,
            Pin = 0xE141,
            Placeholder = 0xE18A,
            Play = 0xE102,
            PostUpdate = 0xE1D7,
            Preview = 0xE295,
            PreviewLink = 0xE12A,
            Previous = 0xE100,
            Print = 0xE749,
            Priority = 0xE182,
            ProtectedDocument = 0xE131,
            Read = 0xE166,
            Redo = 0xE10D,
            Refresh = 0xE149,
            Remote = 0xE148,
            Remove = 0xE108,
            Rename = 0xE13E,
            Repair = 0xE15E,
            RepeatAll = 0xE1CD,
            RepeatOne = 0xE1CC,
            ReportHacked = 0xE1DE,
            ReShare = 0xE1CA,
            Rotate = 0xE14A,
            RotateCamera = 0xE124,
            Save = 0xE105,
            SaveLocal = 0xE159,
            Scan = 0xE294,
            SelectAll = 0xE14E,
            Send = 0xE122,
            SetLockScreen = 0xE18C,
            SetTile = 0xE18D,
            Setting = 0xE115,
            Share = 0xE72D,
            Shop = 0xE14D,
            ShowBcc = 0xE169,
            ShowResults = 0xE15C,
            Shuffle = 0xE14B,
            SlideShow = 0xE173,
            SolidStar = 0xE1CF,
            Sort = 0xE174,
            Stop = 0xE15B,
            StopSlideShow = 0xE191,
            Street = 0xE1C3,
            Switch = 0xE13C,
            SwitchApps = 0xE1E1,
            Sync = 0xE117,
            SyncFolder = 0xE1DF,
            Tag = 0xE1CB,
            Target = 0xE1D2,
            ThreeBars = 0xE1E8,
            TouchPointer = 0xE1E3,
            Trim = 0xE12C,
            TwoBars = 0xE1E7,
            TwoPage = 0xE11E,
            Underline = 0xE19A,
            Undo = 0xE10E,
            UnFavorite = 0xE195,
            UnPin = 0xE196,
            UnSyncFolder = 0xE1DD,
            Up = 0xE110,
            Upload = 0xE11C,
            Video = 0xE116,
            VideoChat = 0xE13B,
            View = 0xE18B,
            ViewAll = 0xE138,
            Volume = 0xE15D,
            WebCam = 0xE156,
            World = 0xE128,
            XboxOneConsole = 0xE990,
            ZeroBars = 0xE1E5,
            Zoom = 0xE1A3,
            ZoomIn = 0xE12E,
            ZoomOut = 0xE1A4
        }
    }
}
