<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="FluentAvaloniaUI" Version="3.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
    <PackageReference Include="SkiaSharp.Svg" Version="1.60.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\IconManager.Core\IconManager.Core.csproj" />
    <ProjectReference Include="..\IconManager.IconSets\IconManager.IconSets.csproj" />
  </ItemGroup>
</Project>
