<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="FluentAvaloniaUI" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.Svg" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\IconManager.Core\IconManager.Core.csproj" />
    <ProjectReference Include="..\IconManager.IconSets\IconManager.IconSets.csproj" />
  </ItemGroup>

  <Target Name="Format XAML" AfterTargets="BeforeBuild" Condition="'$(Configuration)' == 'Debug'">
    <!-- XamlStyler -->
    <Exec Command="dotnet tool install --global XamlStyler.Console" IgnoreExitCode="true" />
    <Exec Command="xstyler.exe --recursive --directory &quot;$(SolutionDir)Source\IconManager&quot; --config &quot;$(SolutionDir)Source\IconManager\XamlStylerConfig.json&quot;" IgnoreExitCode="true" />
  </Target>
</Project>
